language: python 

python: 
  - "3.6"

addons:
  postgresql: "9.6"

install: 
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'CREATE DATABASE mytestdb;' -U postgres

script:
  - python manage.py test
  - coverage run --source=. manage.py test

after_success:
  - coveralls

notifications:
  slack: andela:vCdyou7U6ORP2TFMbwCONnGU